(define (define/is? expr) (tagged-list? expr 'define))
(define (define/procedure? expr) (pair? (cadr expr)))
(define (define/params expr) (cdadr expr))
(define (define/name expr) 
  (if (define/procedure? expr)
    (caadr expr)
    (cadr expr)))
(define (define/body expr)
  (if (define/procedure? expr)
    (cddr expr)
    (caddr expr)))
(define (define/eval expr env)
  (if (define/procedure? expr)
    (env/define! env (define/name expr) (procedure/make (define/params expr) (define/body expr)))
    (env/define! env (define/name expr) (evaluate (define/body expr) env)))
  '())

(evaluator/set-handler! global-evaluator define/is? define/eval) 
